/*
 * Copyright  2020  Chamlal.Mohamed
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.twiza;


import com.twiza.domain.ESheet;
import com.twiza.domain.EWorkbook;
import com.twiza.domain.ExcelWorkbook;
import com.twiza.utils.ExcelReader;
import com.twiza.utils.ExcelWriter;

public class App {
    public static String testFile = "C:\\Users\\mohamed.chamlal\\.gitforexcel\\" +
                                            "plausibilityFile.xlsx";
    private static String oldFilePath = "C:\\Users\\mohamed.chamlal\\.gitforexcel\\TestFiles\\9837663080OR00-000 Max Wire List.xlsx";
    private static String newFilePath = "C:\\Users\\mohamed.chamlal\\.gitforexcel\\TestFiles\\9837663080OR00-020 Max Wire List.xlsx";
    private static String diffFilePath = "C:\\Users\\mohamed.chamlal\\.gitforexcel\\TestFiles\\diff-NEW.xlsx";

    public static void main(String[] args) {
        try {


            ESheet newSheet = ExcelReader.getInstance().readWorkbook(newFilePath)
                                         .getSheet("Report(Draft)")
                                         .adoptFirstRowAsHeaders(true)
                                         .setKeyIndexes(2,5);
            ESheet oldSheet = ExcelReader.getInstance().readWorkbook(oldFilePath)
                                         .getSheet("Report(Draft)")
                                         .adoptFirstRowAsHeaders(true)
                                         .setKeyIndexes(2,5);
            oldSheet.matchWithTemplate(newSheet.getHeaders(), ESheet.TemplateMode.CONCAT);
            newSheet.matchWithTemplate(oldSheet.getHeaders(), ESheet.TemplateMode.CONCAT);
            EWorkbook workbook = new ExcelWorkbook();
            workbook.addSheet(newSheet.compare(oldSheet));
            ExcelWriter.getInstance().writeToWorkbook(diffFilePath, workbook);
//            System.out.println("Old sheet headers-------------------------");
//            System.out.println(oldSheet.getHeaders());
//            System.out.println("New sheet headers-------------------------");
//            System.out.println(newSheet.getHeaders());
//            System.out.println(oldSheet.getHeaders().equals(newSheet.getHeaders()));
//            EWorkbook workbook = new ExcelWorkbook();
//            workbook.addSheet(newSheet.compare(oldSheet));
//            ExcelWriter.getInstance().writeToWorkbook(diffFilePath, workbook);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


}
