/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.twiza.utils;

import com.twiza.excel.ERow;

import java.io.File;
import java.io.FileNotFoundException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

/**
 * @author nabel
 * */

public class ResourceHelper {

    private static final String FILE_NOT_FOUND_IN_RESOURCES = "File not found in resources ";

    /**
     * Get the File from resources
     *
     * @param resourcesFile properties file from resources directory
     * @return the associated File
     * @throws FileNotFoundException if the resource file not found
     */
    public static File getResourceFile(String resourcesFile) throws FileNotFoundException {
        if (resourcesFile == null) {
            throw new FileNotFoundException(FILE_NOT_FOUND_IN_RESOURCES + resourcesFile);
        }
        URL url;
        try {
            url = ResourceHelper.class.getClassLoader().getResource(resourcesFile);
        } catch (final SecurityException e) {
            throw new FileNotFoundException(FILE_NOT_FOUND_IN_RESOURCES + resourcesFile);
        }
        if (url == null) {
            url = Thread.currentThread().getContextClassLoader().getResource(resourcesFile);
        }
        if (url == null) {
            throw new FileNotFoundException(FILE_NOT_FOUND_IN_RESOURCES + resourcesFile);
        }
        File file;
        try {
            file = new File(url.toURI());
        } catch (final URISyntaxException e) {
            file = new File(url.getFile().replaceAll("%20", " "));
        }
        if (file.exists()) {
            return file;
        }
        throw new FileNotFoundException(FILE_NOT_FOUND_IN_RESOURCES + resourcesFile);
    }

    public static void printMap(Map<String, ERow> map) {
        Iterator<String> rows = map.keySet().iterator();
        while (rows.hasNext()) {
            String key = (String) rows.next();
            System.out.print(key + " :");
            Iterator rowsElements = ((List) map.get(key).getElements()).iterator();

            while (rowsElements.hasNext()) {
                String value = (String) rowsElements.next();
                System.out.print(value + "-");
            }

            System.out.println();
        }

    }
}
